### ISSUE TITLE
Where is .htaccess file

### ISSUE THREAD

**Issue by GysLTB** [issue-tracking-system/Project-Management-Software#1]
Hi.

Where is .htaccess file?

now, I using
```
RewriteEngine on
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(?:([^/]+)|)(?:/([^/]+)|)/?$ index.php?page=$1&sub-page=$2 [L,QSA]
```
but not related parameters are transmitted

**Comment by kirilkirkov** [comment]
@chockob Hello. I add htaccess file with this commit - https://github.com/issue-tracking-system/pmTicket/commit/be835cd445fd31470c66c57e10c78f7161cd02a8
