### ISSUE TITLE
Missing Folder for Login and User Profile Images

### ISSUE THREAD

**Issue by DennisBrieske** [issue-tracking-system/Project-Management-Software#10]
Hi,

first let me say, it is a great PM-Software :-)

I have found two Bugs in the current branch.

1. Its not possible to upload a Login Image
2. Its not possible to upload Users Profile Image

The problem can be fix by add these Folders to Project-Main-Folder:

attachments/global/login_image/
attachments/global/users_profile/

Reegards
Dennis

**Comment by kirilkirkov** [comment]
@DennisBrieske 
Thank you! 😊
I will fix that issue.
