### ISSUE TITLE
HTTP Error 404.0 - Not Found

### ISSUE THREAD

**Issue by logicchild0x00** [issue-tracking-system/Project-Management-Software#17]
Hi,
I configured the database, and uploaded it to IIS web server, and when running the site, I logged in with default credentials, and once I pressed Login, the server returned HTTP Error 404.0 - Not Found, and the URL was: https://www.maindomain.com/subdomain/home

I checked the folder, and found the pages inside a folder "_html_parts"!

**Comment by kirilkirkov** [comment]
@logicchild0x00  The your server must read the .htaccess file.
