### ISSUE TITLE
Bug found

### ISSUE THREAD

**Issue by teguh02** [issue-tracking-system/Project-Management-Software#18]
When i'm add user with Profession, i'm found this error

![image](https://user-images.githubusercontent.com/43981051/98067443-1f0afa80-1e8c-11eb-87e9-9ffcfdcf11ec.png)

![Opera Snapshot_2020-11-04_105149_dr gtoc store](https://user-images.githubusercontent.com/43981051/98067401-1286a200-1e8c-11eb-81c5-1aaa3dd62f55.png)

**Comment by kirilkirkov** [comment]
@teguh02 
you must add professions and choose one before add users.

**Comment by kirilkirkov** [comment]
@teguh02 
That field can not be empty
