### ISSUE TITLE
Issued installing on Debian 10 and 11

### ISSUE THREAD

**Issue by fernandodiacenco** [issue-tracking-system/Project-Management-Software#19]
Hi there!

After installing on Debian 11, lamp and all that, I got this error

> [Wed Aug 18 16:35:20.951456 2021] [php7:error] [pid 10340] [client 192.168.20.71:56610] PHP Fatal error:  Uncaught Error: Call to undefined function $

Same thing on Debian 10, I suspected the PHP version, so i downgraded it to php5, and the error changed to:

> [Wed Aug 18 16:56:07.368919 2021] [:error] [pid 20654] [client 192.168.20.71:56880] PHP Fatal error:  Call to undefined function mb_internal_encoding() in /var/www/html/inc/config.php on line 7

After commenting the line, ignoring the file warning me not to change anything, and restarting apache, browsing the server I got the message: Come back later!

![image](https://user-images.githubusercontent.com/2643364/129964265-8c5cedf2-ab8d-4085-a5b3-b4dd25634ba2.png)

So I suspect I did something really wrong, but i'm not sure what. Can you guide me? Thanks!

Here is the step by step of my installation process:

> sudo su
> 
> apt install apache2 php mariadb-server git
> 
> mysql_secure_installation
> 
> cd /var/www/html
> 
> git clone https://github.com/issue-tracking-system/Project-Management-Software.git && cd Project-Management-Software
> 
> mv * /var/www/html && cd .. && sudo rm -rf Project-Management-Software
> 
> mysql -u root
> 
> CREATE DATABASE pmticket;
> 
> GRANT ALL PRIVILEGES ON pmticket.* TO 'root'@'localhost';
> 
> QUIT;
> 
> mysql -u root -p pmticket < DATABASE.sql
> 
> nano /var/www/html/inc/db.php
> 
> //Database config
> define('HOST', 'localhost');
> define('USER', 'root');
> define('PASS', 'mypasswordhere');
> define('DATABASE', 'pmticket');
> 
> service mariadb restart && service apache2 restart

**Comment by kirilkirkov** [comment]
Hello @fernandodiacenco ,
go to inc directory and open settings.php file, there you will find constant with name DEBUG_MODE, change its value to TRUE and you will see the exact error.
I can't tell you the reason for that error without the exception message
