### ISSUE TITLE
The requested URL /home was not found on this server.

### ISSUE THREAD

**Issue by fernandodiacenco** [issue-tracking-system/Project-Management-Software#2]
Hello,

Trying to install PM Ticket on a clean virtual machine running Ubuntu 16.04, first i came across this error:

> [:error] [pid 1082] [client 10.0.0.50:54858] PHP Fatal error:  Uncaught Error: Call to undefined function mb_internal_encoding() in /var/www/html/pmticket/inc/config.php:7\nStack trace:\n#0 /var/www/html/pmticket/classes/class.main.php(13): require_once()\n#1 /var/www/html/pmticket/index.php(11): require_once('/var/www/html/p...')\n#2 {main}\n  thrown in /var/www/html/pmticket/inc/config.php on line 7

The config.php file mentions a big **DOT NOT CHANGE ANYTHING IN THIS FILE** on line 6

Googling the error returns the necessity of having php-mbstring package installed, so **apt install php-mbstring -y** with **service apache2 restart** fixed this issue

But them, on first login (using admin / admin) returns  404, The requested URL /home was not found on this server.

The apache error.log file shows this: 

> [:error] [pid 1553] [client 10.0.0.50:55058] PHP Notice:  Use of undefined constant ACCOUNT_DOMAIN - assumed 'ACCOUNT_DOMAIN' in /var/www/html/pmticket/inc/config.php on line 44

Here is the line 44 mentioned:

> $CONFIG['IMAGESSPACESUPLOADDIR'] = 'attachments/' . ACCOUNT_DOMAIN . '/space_logos/'; //SPACE IMAGES

At first i thought it was a problem on the distro, because Ubuntu 16.04 uses php7, so I've made a clean install on Ubuntu 14.04 which uses php5 (installing the package libapache2-mod-php5 instead of php-mbstring), the exact same thing happens, 404 the requested url /home was not found on this server

I'm stuck, how can I fix this and start using PM Ticket?

Thanks.

**Comment by kirilkirkov** [comment]
Are you sure that your index.php is like this https://github.com/issue-tracking-system/pmTicket/blob/master/index.php
and your .htaccess file is in root directory and apache loads him?

**Comment by kirilkirkov** [comment]
It is written on PHP 5 and dont have problems. I test it on PHP 7 and also works great. Maybe your apache server dont load .htaccess file or you are make code changes.
