### ISSUE TITLE
Dead or Alive ? 

### ISSUE THREAD

**Issue by fdefilippo** [issue-tracking-system/Project-Management-Software#20]
Hi, a first question: is the project dead or alive ? Do tickets support attachments? 

![image](https://user-images.githubusercontent.com/16714986/136513588-65075757-e4a2-4d31-9056-eefa7793a628.png)

thank you

**Comment by kirilkirkov** [comment]
@fdefilippo 
Hello, the project currently is not supported. Attachments are not available for the tasks
