### ISSUE TITLE
 Trying to access array offset

### ISSUE THREAD

**Issue by SemangkukMaggi** [issue-tracking-system/Project-Management-Software#21]
Trying to access array offset on value of type null in C:\xampp\htdocs\Projek_Intern\classes\class.database.php on line 72

How to solve this, i got this at login page. After key in username and password it just stay at login page
![image](https://user-images.githubusercontent.com/103620229/214767891-d4dbee1b-b315-47e1-9d20-dde939a7bbc7.png)

**Comment by kirilkirkov** [comment]
Hey @SemangkukMaggi 
What is your PHP Version?

**Comment by SemangkukMaggi** [comment]
currently using phpmyadmin(web), xampp v3.3.0

**Comment by SemangkukMaggi** [comment]
php version 8.2.1

**Comment by kirilkirkov** [comment]
@SemangkukMaggi 
Its fixed, this error should not appear anymore
