### ISSUE TITLE
issue log in admin or maybe i was wrong?

### ISSUE THREAD

**Issue by remajajambang** [issue-tracking-system/Project-Management-Software#22]
![image](https://github.com/issue-tracking-system/Project-Management-Software/assets/134618322/77442dca-82dd-4e5c-aa56-68d395dce18b)

**Comment by kirilkirkov** [comment]
Hello @remajajambang 
you can disable the debug mode from **/inc/settings.php** -> define('DEBUG_MODE', FALSE);
About the login credentials, yes if you have already imported DATABASE.sql, the username and password should be - admin
