### ISSUE TITLE
No styling. why

### ISSUE THREAD

**Issue by TonyTaboy** [issue-tracking-system/Project-Management-Software#24]
![NOT WORKING](https://github.com/user-attachments/assets/6b08be5b-4cfa-4a47-9839-fc0b7acefb44)

**Comment by kirilkirkov** [comment]
Can you show me the console of the browser into the Network tab? There is some problem with your server configuration so the styles are not loaded.

**Comment by TonyTaboy** [comment]
![image](https://github.com/user-attachments/assets/e10b8f96-d0fd-422e-a1ad-a07561d55012)

**Comment by TonyTaboy** [comment]
![image](https://github.com/user-attachments/assets/693ce961-f740-4cb2-83b9-85c73700c235)
![image](https://github.com/user-attachments/assets/e62cc18a-875c-4364-90c8-2b421fd6628a)

**Comment by kirilkirkov** [comment]
Did you use Apache as a web server? The server should successfully read the .htaccess file and everything should work from your index.php file.
If you use nginx, you should add the .htaccess rules to it

**Comment by TonyTaboy** [comment]
![image](https://github.com/user-attachments/assets/1d6b0674-e961-4305-8426-4bbc15ed8db3)

**Comment by kirilkirkov** [comment]
@TonyTaboy 
Can you try again? I have uploaded a new version with fixes for php 7. Please pull the latest code of the repository.
Also please make sure that mod_rewrite into your Apache is enabled.

**Comment by TonyTaboy** [comment]
![image](https://github.com/user-attachments/assets/bbeee57f-ccf0-46e4-b98e-9f4948d2e175)
Its working. Thanks man

**Comment by kirilkirkov** [comment]
You are welcome!
