### ISSUE TITLE
Database error

### ISSUE THREAD

**Issue by devorator** [issue-tracking-system/Project-Management-Software#3]
I am getting Database error when trying to add user from form.

**Comment by kirilkirkov** [comment]
@devorator Can you try again with this fixes:
https://github.com/issue-tracking-system/Project-Management-Software/commit/b57219a0c2ed808c99d6376172cac046a1093206
https://github.com/issue-tracking-system/Project-Management-Software/commit/717e72ed18b65020b2736db026c63f487fbe9dd8

And also this (for more performance :) - https://github.com/issue-tracking-system/Project-Management-Software/commit/d2897e3b46bc90c927a4c5959194e4eee841907d

I wait to tell me is everything alright

**Comment by devorator** [comment]
Thank you
