### ISSUE TITLE
404 

### ISSUE THREAD

**Issue by ashkan84f** [issue-tracking-system/Project-Management-Software#4]
Hi,
I can run the project on my local Apache. But when I moved it to my CPanel host, after logging in I see the following screen:

Not Found
The requested URL /issuetracker/home was not found on this server.
Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

**Comment by kirilkirkov** [comment]
@arashk72  Do you have .htaccess file? Check the directory of issuetracker for .htaccess

**Comment by ashkan84f** [comment]
I have the htaccess file in the root directoy (i.e public_html) and the content of htaccess file is:

DirectoryIndex index.html index.php index.htm parking-page.html


The issue tracker system is parker under public_html/issuetracker.

**Comment by ashkan84f** [comment]
is there any way that I can have the issue tracker system in a sub folder under public_html?

**Comment by kirilkirkov** [comment]
@arashk72 In public_html/issuetracker you must have .htaccess file with content:

RewriteEngine on
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule .*public/hash/(.*) _html_parts/wiki/public_preview.php?hash=$1 [L]

RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ([a-zA-Z]+) index.php?page=$1 [L,QSA]

**Comment by ashkan84f** [comment]
Thanks for the solution.
BTW you have done a nice job. Thanks.
