### ISSUE TITLE
problem to add user and 

### ISSUE THREAD

**Issue by saket61195** [issue-tracking-system/Project-Management-Software#6]
i am using xampp  
Username was taken! Choose another one
and
Notice: Use of undefined constant ACCOUNT_DOMAIN - assumed 'ACCOUNT_DOMAIN' in C:\xampp\htdocs\Project-Management-Software-master\inc\config.php on line 40

Notice: Use of undefined constant ACCOUNT_DOMAIN - assumed 'ACCOUNT_DOMAIN' in C:\xampp\htdocs\Project-Management-Software-master\inc\config.php on line 41

Notice: Use of undefined constant ACCOUNT_DOMAIN - assumed 'ACCOUNT_DOMAIN' in C:\xampp\htdocs\Project-Management-Software-master\inc\config.php on line 42

Notice: Use of undefined constant ACCOUNT_DOMAIN - assumed 'ACCOUNT_DOMAIN' in C:\xampp\htdocs\Project-Management-Software-master\inc\config.php on line 44

**Comment by saket61195** [comment]
;error_reporting=E_ALL & ~E_DEPRECATED & ~E_STRICT

problem solved

**Comment by kirilkirkov** [comment]
@saket61195 It is good to check why "SELECT id, company, domain FROM accounts WHERE domain = '" . $domain . "' AND active = 1 LIMIT 1" dont return any results. Maybe you must add account
This query is in classes/class.subdomain.php
