### ISSUE TITLE
Warning: Use of undefined constant ACCOUNT_DOMAIN - assumed 'ACCOUNT_DOMAIN' (this will throw an Error in a future version of PHP)

### ISSUE THREAD

**Issue by Paul75** [issue-tracking-system/Project-Management-Software#7]
Warning: Use of undefined constant ACCOUNT_DOMAIN - assumed 'ACCOUNT_DOMAIN' (this will throw an Error in a future version of PHP)

**Comment by kirilkirkov** [comment]
@Paul75  It is good to check why "SELECT id, company, domain FROM accounts WHERE domain = '" . $domain . "' AND active = 1 LIMIT 1" dont return any results. Maybe you must add account
This query is in classes/class.subdomain.php
