### ISSUE TITLE
Issue With Config File

### ISSUE THREAD

**Issue by sivag512** [issue-tracking-system/Project-Management-Software#8]
After Deploying the Project with my server i have the Warning messages with the Configuration File 
The Errors are shown as below 
Warning: Use of undefined constant ACCOUNT_DOMAIN - assumed 'ACCOUNT_DOMAIN' (this will throw an Error in a future version of PHP) in E:\xampp\htdocs\pdm\inc\config.php on line 40

Warning: Use of undefined constant ACCOUNT_DOMAIN - assumed 'ACCOUNT_DOMAIN' (this will throw an Error in a future version of PHP) in E:\xampp\htdocs\pdm\inc\config.php on line 41

Warning: Use of undefined constant ACCOUNT_DOMAIN - assumed 'ACCOUNT_DOMAIN' (this will throw an Error in a future version of PHP) in E:\xampp\htdocs\pdm\inc\config.php on line 42

Warning: Use of undefined constant ACCOUNT_DOMAIN - assumed 'ACCOUNT_DOMAIN' (this will throw an Error in a future version of PHP) in E:\xampp\htdocs\pdm\inc\config.php on line 44

**Comment by kirilkirkov** [comment]
@sivag512 must define it in class.subdomain
