### ISSUE TITLE
Come back Later - No mysqi extension - Exception

### ISSUE THREAD

**Issue by amardimiaty** [issue-tracking-system/Project-Management-Software#9]
![image](https://user-images.githubusercontent.com/64644450/82170575-e5dad000-98d5-11ea-8d30-c9f93b174007.png)

![image](https://user-images.githubusercontent.com/64644450/82170611-030f9e80-98d6-11ea-9681-1a0de2204786.png)

**Comment by kirilkirkov** [comment]
@amardimiaty
Hello. You have some Exception. Try to set DEBUG_MODE to TRUE in inc/settings.php to see the real exception message or check logs in logs/errors.log.

**Comment by amardimiaty** [comment]
HI I'm getting this error 

New Exception: No MYSQLi extension

**Comment by kirilkirkov** [comment]
You do not have mysqli extension for php. Check in Google how to install it for the operation system that you use.

**Comment by amardimiaty** [comment]
I'm using ubuntu and it is already installed

**Comment by amardimiaty** [comment]
php7.1-mysql - MySQL module for PHP
php7.1-odbc - ODBC module for PHP
php7.1-opcache - Zend OpCache module for PHP
php7.1-pgsql - PostgreSQL module for PHP
php7.1-phpdbg - server-side, HTML-embedded scripting language (PHPDBG binary)
php7.1-pspell - pspell module for PHP
php7.1-readline - readline module for PHP
php7.1-recode - recode module for PHP
php7.1-snmp - SNMP module for PHP
php7.1-soap - SOAP module for PHP
php7.1-sqlite3 - SQLite3 module for PHP
php7.1-sybase - Sybase module for PHP
php7.1-tidy - tidy module for PHP
php7.1-xml - DOM, SimpleXML, WDDX, XML, and XSL module for PHP
php7.1-xmlrpc - XMLRPC-EPI module for PHP
php7.1-xsl - XSL module for PHP (dummy)
php7.1-zip - Zip module for PHP

**Comment by kirilkirkov** [comment]
if(!class_exists('mysqli')) {
            throw new Exception("No MYSQLi extension");
}

Check your configurations. Your Mysqli class not exists
